export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const SEARCH_COUNTRY_BY_NAME = "SEARCH_COUNTRY_BY_NAME";
export const SEARCH_COUNTRY_BY_ID = "SEARCH_COUNTRY_BY_ID";
export const POST_ACTIVITY = "ADD_ACTIVITY";
export const SEARCH_BY_ACTIVITY = "SEARCH_BY_ACTIVITY";
export const SEARCH_BY_CONTINENT = "SEARCH_BY_CONTINENT";

export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_BY_POPULATION = "ORDER_BY_POPULATION";
