export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const SEARCH_COUNTRY_BY_NAME = "SEARCH_COUNTRY_BY_NAME";
export const SEARCH_COUNTRY_BY_ID = "SEARCH_COUNTRY_BY_ID";
export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const SEARCH_BY_ACTIVITY = "SEARCH_BY_ACTIVITY";
export const SEARCH_BY_CONTINENT = "SEARCH_BY_CONTINENT";

//FALTAN HACER
export const ORDER_AZ = "ORDER_AZ";
export const ORDER_ZA = "ORDER_ZA";
export const ORDER_POPULATION_ASC = "ORDER_POPULATION_ASC";
export const ORDER_POPULATION_DES = "ORDER_POPULATION_DES";
